### ISSUE TITLE
Cursors for Icon buttons/links

### ISSUE THREAD

**Issue by ghost** [anoadragon453/ZeroLSTN#2]
https://github.com/anoadragon453/ZeroLSTN/blob/226579a32009cb13ca0554aedf4c19fc177c9b07/src/vue_components/song_item.vue#L18

You have `@click.prevent` which will run something when clicked. However, in order for anchor links to get the pointer cursor on hover, you either need the css `cursor: pointer`, or just put `href="#"` (btw the `.prevent` will make it so that it won't navigate to whatever is in `href`).

**Comment by anoadragon453** [comment]
Oh, I was wondering how to get the buttons have a proper cursor. Thanks!

**Comment by anoadragon453** [comment]
Fixed with a simple css rule in b20dc45363632d56eccb058ec862ba5c7d100844
